### ISSUE TITLE
psc-package npm package doesn't work on windows

### ISSUE THREAD

**Issue by doolse** [purescript/psc-package#100]
It says the psc-package.exe doesn't exist. If you manually copy the binary into the `node_modules/psc-package/vendor/` dir it works fine.

**Comment by justinwoo** [comment]
Related issue: https://github.com/joneshf/node-psc-package-bin/issues/1

No idea how the upstream package https://github.com/purescript-contrib/node-purescript works and why this would be different though.

**Comment by joneshf** [comment]
I'm thinking about deprecating that repo. I've no more skin the `psc-package` game and don't really want to maintain it anymore. Primarily, I don't understand the code and it's got problems on windows. It's also really weird to be beholden to the version numbers of this repo and would prefer to not deal with that either.

If you'd like to take over the npm package name, I'm more than happy to transfer it (if that's possible).

**Comment by justinwoo** [comment]
Anyone following the link should look through https://psc-package.readthedocs.io/en/latest/installation.html

**Comment by justinwoo** [comment]
Closing as this issue has no other actions. Windows users will want to use Chocolatey: https://chocolatey.org/packages/psc-package
