### ISSUE TITLE
add-from-bower not working on Windows

### ISSUE THREAD

**Issue by stkb** [purescript/psc-package#110]
$ psc-package add-from-bower whatever
    psc-package.exe: bower: createProcess: does not exist (No such file or directory)

I guess this is the same thing as other commands not working on Windows, though there isn't really a workaround for this as there's no `bower.exe` file.

**Comment by justinwoo** [comment]
Do you have bower installed? I haven't heard of anyone not being able to use this from Windows before.

**Comment by stkb** [comment]
For sure :) (installed from npm)

    $ bower --version
    1.8.4

    $ where bower
    C:\Users\Steve\Apps\nodejs\bower
    C:\Users\Steve\Apps\nodejs\bower.cmd

It's the same in Bash (from Git for Windows) or CMD. I did try removing the first (shell script) file just leaving the `.cmd`, but still no luck in either shell.

However I did work around it by manually creating a `bower.exe` shim that calls the `bower.cmd` file (and putting it in the same folder). Then it works.

Is this not the same problem as with `purs`? (#34)

**Comment by stkb** [comment]
Hit the wrong button :)

**Comment by justinwoo** [comment]
I wouldn't know (I don't use Windows anymore), but there are other major contributors and users who use Windows so you might ask this on slack/discourse.

**Comment by nwolverson** [comment]
Given add-from-bower is removed, I think this can be closed?

**Comment by justinwoo** [comment]
Yup😃
