### ISSUE TITLE
add-from-bower complaining about a missing repository field

### ISSUE THREAD

**Issue by naglalakk** [purescript/psc-package#111]
Hi. I'm trying to add this package from bower: https://github.com/Unisay/purescript-facebook
but I get the following error:

    Errors processing Bower Info: Error in $.latest: key "repository" not present

but looking at the bower.json file in this repo it does have a repository field. 
Is there anything missing from this repo that I could add for this to work?

**Comment by justinwoo** [comment]
I'd check what version of psc-package you're using, `psc-package add-from-bower purescript-facebook` works without a problem for me.

**Comment by naglalakk** [comment]
ahh right that could be it. I have version 0.3.2. If I try the command you mention above I get "packages.json does not exist". Should I be at the latest version 0.3.3 - pre2?

**Comment by justinwoo** [comment]
Probably, but you should also check your version of bower then. I have 1.8.4

**Comment by naglalakk** [comment]
Updated bower and psc-package and it's the same. Why would it tell me "packages.json does not exist". What is this error reffering to? psc-package.json is suppose to contain a source pointing to a set correct?   

This is my psc-package file

```
{
  "name": "dj-competition-vote",
  "set": "psc-0.11.7",
  "source": "https://github.com/purescript/package-sets.git",
  "depends": [
    "affjax",
    "aff",
    "halogen",
    "debug",
    "foreign-generic",
    "generics-rep",
    "psci-support",
    "console",
    "eff",
    "prelude",
    "lists"
  ]
}
```

Also I'm wondering if I can add this from git url instead because there are two versions of purescript-facebook going on and I don't know which one psc-package is choosing. 
Should I be able to do

`psc-package add-from-bower https://github.com/Unisay/purescript-facebook`

**Comment by justinwoo** [comment]
Wait, are you running this command from a `package-sets` repo? You don't use `add-from-bower` from a project. See https://github.com/purescript/psc-package#add-a-package-to-the-package-set

**Comment by naglalakk** [comment]
I'm just trying to use a package from bower with psc-package. Is this not possible? 
I don't fully understand the package-sets thing. I thought the set and source were referring to the general path psc-package uses to resolve dependencies.

**Comment by justinwoo** [comment]
A package set is a repo with tags for a collection of packages. `add-from-bower` is a command for editing package sets quickly.

Your project consumes a package set that you have already prepared.

You might want to read a post I made on how to prepare a package set (https://qiita.com/kimagure/items/c37b228e80318d4158f0#add-it-to-your-package-set) and re-read the README of psc-package to understand what a package set is.

**Comment by naglalakk** [comment]
ahh ok wow my understanding was totally off. So I can prepare my own package set by for example:

- cloning https://github.com/purescript/package-sets.git
- cd into that folder and do psc-package add-from-bower purescript-facebook
- push the changes to my forked repo
- add package-sets name and source to the psc-package.json file that will use it

is this a correct understanding of how it works?

**Comment by justinwoo** [comment]
Yeah, that's about it. One thing to be careful of is to push tags to your repo, unless you do want to deal with a mutable package set from a branch.

**Comment by naglalakk** [comment]
Thank you so much for clearing this up @justinwoo. Closing this now
