### ISSUE TITLE
Creating a custom set with purescript-aff not working

### ISSUE THREAD

**Issue by naglalakk** [purescript/psc-package#112]
Steps to reproduce

- Cloned purescript/package-sets to purescript/package-sets
- Added purescript-aff from bower (why is this not in the default package-sets?) 
- Tagged and pushed my changes (tags are not mentioned at all in the docs but they are vital for this to work) 
- Added my tag "aff.set-may-27-2018" to "sets" in psc-package.json and source "https://github.com/naglalakk/package-sets"
- Run psc-package install

I get `Package aff does not exist in package set`

But it is?

```
  "aff": {
    "dependencies": [
      "datetime",
      "effect",
      "exceptions",
      "functions",
      "parallel",
      "transformers",
      "unsafe-coerce"
    ],
    "repo": "git://github.com/slamdata/purescript-aff.git",
    "version": "v5.0.0"
  },
```

**Comment by justinwoo** [comment]
The current master package set only contains the core libraries and will have more libraries added over time.

In you project (not your package set) repo, you should not have this problem if you install the package set by setting psc-package.json.

**Comment by justinwoo** [comment]
You might want to ask someone in #purescript-beginners on slack or on discourse. The issues here should be for bugs in psc-package.

**Comment by naglalakk** [comment]
"In you project (not your package set) repo, you should not have this problem if you install the package set by setting psc-package.json"

I'm not sure I follow. Do I need to do anything after I add aff to my package set repo?. That is to say in my project repo do I need to do anything other than change the set variable in psc-package.json? 
Everytime i try to do something else it tells me that aff does not exist

**Comment by naglalakk** [comment]
Ok I will move my discussion to slack or discourse. But in my view the documentation is a bug that needs to be discussed and verified
