### ISSUE TITLE
psc-package init fails "Remote branch psc-0.12.0 not found in upstream origin"

### ISSUE THREAD

**Issue by Euregan** [purescript/psc-package#115]
I just installed `psc-package `using npm, and when I try to run `psc-package init` it fails stating that 

> Remote branch psc-0.12.0 not found in upstream origin

Indeed, the branch does not exist on the repo.

It works if I specify `psc-package init --set master` though.

**Comment by justinwoo** [comment]
duplicate of https://github.com/purescript/package-sets/issues/182, there will be a 0.12.0 branch when it makes sense

**Comment by Euregan** [comment]
Oh, dang, hadn't seen that one
