### ISSUE TITLE
Give warning on users attempting to prefix `purescript-`

### ISSUE THREAD

**Issue by justinwoo** [purescript/psc-package#120]
e.g. `psc-package install purescript-aff` should warn

**Comment by paf31** [comment]
Now I can't release my `purescript-purescript-parser` library without users getting a warning! :)

**Comment by justinwoo** [comment]
I know right?? I was thinking that it'd be a final check if no package was found, not eager

**Comment by paf31** [comment]
Gotcha. I'll retract my 👎 then.

**Comment by justinwoo** [comment]
Fixed by #125
