### ISSUE TITLE
[QUESTION] Is there a way of using local/private packages?

### ISSUE THREAD

**Issue by NickSeagull** [purescript/psc-package#132]
In my team we are currently trying to build some libraries for private use, until we get them to a stable point where we can release them. Is there a (at least hacky) way of using their private repos or local folders?

I've already setup a fork of `package-sets` but apart from adding open source packages I'm not sure what to do.

Is there a way of achieving this?
Should I switch to bower for this use case?

Thanks in advance :smile:

**Comment by justinwoo** [comment]
First, you might want to read through https://spacchetti.readthedocs.io/en/latest/intro.html

Private repos: if you can git clone it, you can put it in your package set
Local: see link, symlink

You might choose to use my package set with its Dhall-based config, it would be superior to trying to manage packages.json

**Comment by kritzcreek** [comment]
One thing to note is that a local git repo is a git repo like any other, which means`git clone file:///home/NickSeagull/project` works... which means you can put that URL into the package set you're using locally.

**Comment by NickSeagull** [comment]
Great, thank you so much!
