### ISSUE TITLE
Deprecating purify in favor of psc-package

### ISSUE THREAD

**Issue by chrisdone** [purescript/psc-package#134]
Hi all,

I haven't maintained [purify](https://github.com/chrisdone/purify) for over a year, as I haven't done any PureScript work. I came back to it just now, and I've marked it deprecated in favor of psc-package.

In the spirit of the previous purify-template repo--getting up and running quickly and reproducibly (so that the instructions work from now or in 3 years)--I made another template repo:

https://github.com/chrisdone/template-psc-package

In case it's useful for anyone.

**Comment by justinwoo** [comment]
Cool, thanks! Also, you might be interested in the alternative package sets I have that uses Dhall for configs: https://github.com/justinwoo/spacchetti
