### ISSUE TITLE
Some packages aren't found

### ISSUE THREAD

**Issue by razcore-rad** [purescript/psc-package#136]
Recently I've started reading purescript by example going with it with purescript v0.12, wanting to try out psc-packages, but upon reaching chapter 8, one using react, I noticed psc-packages doesn't find some packages for some reason. The entries are in `https://github.com/purescript/package-sets/blob/master/packages.json`, but psc-packages doesn't pick them up. Eg.:

```bash
 $ psc-package available --sort | grep react # nothing - can't find it
 $ psc-package install pux
Package `pux` does not exist in package set
 $ psc-package install react
Package `react` does not exist in package set
```

Any ideas? Thanks.

```bash
 $ psc-package --version
0.4.0
```

Installed with `npm i -g psc-package-bin-simple`

**Comment by justinwoo** [comment]
Have you read through https://psc-package.readthedocs.io/en/latest/intro.html#what-is-a-package-set?

You want to use a package set that has those packages.

**Comment by razcore-rad** [comment]
The default package set is purescript/package-sets

Yes I have and as I have mentioned, react & pux & etc. are in [`https://github.com/purescript/package-sets/blob/master/packages.json`](https://github.com/purescript/package-sets/blob/master/packages.json#L1382) & the latest release archives (which I assume `psc-packages` uses - if not `master` directly). That's why I'm confused, they are in `packages.json`, so what am I missing?!

**Comment by justinwoo** [comment]
a `set` is a tag or branch https://spacchetti.readthedocs.io/en/latest/intro.html

**Comment by razcore-rad** [comment]
indeed... sorry to waste your time, thanks a lot!

**Comment by justinwoo** [comment]
np
