### ISSUE TITLE
psc-package 0.4.1 states 0.4.0 as version

### ISSUE THREAD

**Issue by felixmulder** [purescript/psc-package#137]
Not a major issue by any stretch :)

to recreate:

```
$ psc-package --help
```

prints wrong version at bottom

**Comment by justinwoo** [comment]
That's my fault, I could release this now https://github.com/purescript/psc-package/blob/1529f28a70a2b65b02efe4ddd6e879ced1a85b20/psc-package.cabal#L2

**Comment by justinwoo** [comment]
Give this about 10-20 min to have linux/osx releases and 40 min for Windows https://github.com/purescript/psc-package/releases/tag/v0.4.2

**Comment by felixmulder** [comment]
Hooray :tada:
