### ISSUE TITLE
use npm registry + supporting libraries

### ISSUE THREAD

**Issue by zkat** [purescript/psc-package#14]
Hey! So! Sorry to sealion into your repo like this, but I was having some thoughts and I remembered the ongoing plight of purescript folks as far as package management goes.

It turns out I've been overhauling and rewriting a pretty significant chunk of the npm internals related to downloading/caching/extraction/etc, and the product of that work turned out to be https://npm.im/pacote. It's a completely standalone library and it pretty much supports anything you need in order to install stuff from the npm registry itself. Or, you know. It also has git repository support.

Now, I don't know if y'all are remotely willing to use javascript stuff under the hood to get this implemented, but I'd definitely be interested in helping out, refactoring things, adding features, etc, if it meant it would be of use to y'all. I think pacote would benefit immensely from more than one client app. And y'all would be able to rely on a package that's pretty core to a very widely-used package manager. This stuff turns out to be a lot of work. :)

There's a few constraints for this, of course: this still assumes things are semver (although you could disable support for npm-style semver range resolution. I could even provide a hook for parsing out the multiple versions in packuments). It also assumes you're using the various `dependencies` fields, though tbh you can almost certainly make those look literally however you want cause it mostly just copies them over. If you want specific packument fields available, though, we can find ways to make that work. I don't mind changing the manifest logic a bit or providing hooks 👍 

But anything having to do with `node_modules`, _dependency_ resolution ("ok I have this package, which others should I get"), any logic around how to prepare/finalize/script packages -- that's all completely external to this module. Since it's just a library, all the UX 

Sorry for the blob of text! I hope this is interesting!

**Comment by hdgarrood** [comment]
Thanks! I'll definitely keep this in mind. I'm not sure psc-package is likely to want to use this as AFAIK, psc-package aims to be agnostic to which compiler backend you're using (JS, Lua, Erlang, C++...) but I expect there is somewhere in the ecosystem this will be useful, so I'm glad you've made me aware of it. :)

**Comment by zkat** [comment]
Ok! Good luck with stuff! and if y'all have questions about integrating with the registry or just the various persnickety concerns related to fetching blobs of data from the ether and apparating them into useful stuff, feel free to ping about it or refer to this stuff.

Thanks for the quick and kind response. I guess I'll close this now since you answered my questions. Cheers~

**Comment by bodil** [comment]
Yeah, this stuff should come in handy when somebody tackles the problem of PS packages with dependencies on React etc. It's only tangentially related to psc-package, I guess - it'd just need to support the metadata for something else to get the right packages installed.
