### ISSUE TITLE
psc-package 0.5.0 states 0.4.2 as version

### ISSUE THREAD

**Issue by ianchanning** [purescript/psc-package#143]
In what appears to be similar to #137 when I download and run the 0.5.0 Win64 `psc-package.exe`, it outputs 0.4.2 as the version:

```
C:\Users\Ian\Downloads\psc-package-win64-5.0.0\psc-package>psc-package.exe --version
0.4.2
```

SHA appears to be correct (I had renamed my local copy as I was testing with v4.1.0 to check):

```
SHA1(bundle/win64.tar.gz)= ee4e0a03c0116135c39bc609fbe946211002e798
```

![2018-12-03 00_31_01-calculate file hash](https://user-images.githubusercontent.com/233318/49346451-03d95400-f693-11e8-8e31-b8817080dcd7.png)

Build date appears to be correct (as in 6 days ago that matches the release date):

![2018-12-03 00_34_56-psc-package exe properties](https://user-images.githubusercontent.com/233318/49346482-71858000-f693-11e8-960c-930b799c9419.png)

**Comment by justinwoo** [comment]
Yeah, this is my fault. Sorry. I should at least update this

**Comment by justinwoo** [comment]
Hopefully fixed when this builds: https://github.com/purescript/psc-package/releases/tag/v0.5.1

**Comment by ianchanning** [comment]
No problem, only confused me slightly. Thanks for the fixes!

The great thing is that this fixes a bug I was having with trying to get panwriter building on Windows https://github.com/mb21/panwriter/issues/2#issuecomment-443550773

**Comment by ianchanning** [comment]
Thanks, the version I get is 5.1.0 now.
