### ISSUE TITLE
psc-package init with purescript 0.12.2

### ISSUE THREAD

**Issue by wjsetzer** [purescript/psc-package#147]
Purescript was updated a few days ago and it looks like currently psc-package isn't able to work with the new version.

**Comment by justinwoo** [comment]
What are you reporting in this issue? I did just now release purescript/package-sets tag "psc-0.12.2", so that will now install and work. Otherwise, the version it tries to use depends on the version of PureScript you have installed.

**Comment by wjsetzer** [comment]
Oops. I wasn't explicit, sorry. 

`Psc-package init` was failing because it was unable to fetch a 0.12.2 branch.

**Comment by justinwoo** [comment]
Should work now, either by a new `init` or `install`

**Comment by wjsetzer** [comment]
It does indeed work now. Thanks!
