### ISSUE TITLE
psc-package.cabal version field out of sync with v0.6.1 release tag

### ISSUE THREAD

**Issue by mattaudesse** [purescript/psc-package#162]
https://github.com/purescript/psc-package/releases/tag/v0.6.1

```bash
$ git show-ref v0.6.1
01263f559a87a36ccacb5fef9c2b4b88282730f3 refs/tags/v0.6.1
```

https://github.com/purescript/psc-package/blob/01263f559a87a36ccacb5fef9c2b4b88282730f3/psc-package.cabal#L2

Thanks for fixing `stack build` BTW!

**Comment by justinwoo** [comment]
Nice, looks like I dropped a commit or something. Time for yet another release

**Comment by justinwoo** [comment]
Give this maybe 30 min or so: https://github.com/purescript/psc-package/releases/tag/v0.6.2

**Comment by mattaudesse** [comment]
Thanks @justinwoo
