### ISSUE TITLE
Build failed (probably due to optparse-applicative-0.16)

### ISSUE THREAD

**Issue by mitchblank** [purescript/psc-package#166]
Issue checklist:

- [X] Is this a bug?
- [X] Have you read the relevant documentation for Psc-Package? https://psc-package.readthedocs.io/en/latest/
- [NO] Is this a question about package sets? Have you read the Psc-Package documentation or Spacchetti documentation about Psc-Package? https://spacchetti.readthedocs.io/en/latest/intro.html

- Which platform do you have this bug in?

Mac OS 11.4 (Intel)
ghc-8.6.5

- What is the expected behavior?

Build completes

- What is the actual behavior?

```
[3 of 3] Compiling Main             ( app/Main.hs, dist/build/psc-package/psc-package-tmp/Main.o )

app/Main.hs:601:50: error:
    • Couldn't match expected type ‘Opts.ParseError’
                  with actual type ‘Maybe String -> Opts.ParseError’
    • Probable cause: ‘Opts.ShowHelpText’ is applied to too few arguments
      In the third argument of ‘Opts.parserFailure’, namely
        ‘Opts.ShowHelpText’
      In the second argument of ‘($)’, namely
        ‘Opts.parserFailure
           Opts.defaultPrefs pinfo Opts.ShowHelpText mempty’
      In the expression:
        Opts.Failure
          $ Opts.parserFailure
              Opts.defaultPrefs pinfo Opts.ShowHelpText mempty
    |
601 |       Opts.parserFailure Opts.defaultPrefs pinfo Opts.ShowHelpText mempty
    |                                                  ^^^^^^^^^^^^^^^^^
```

- What would help fix this issue?

Based on some googling it seems that a very similar error has bitten other projects due to optparse-applicative being upgraded to 0.16.  For example see https://github.com/nmattia/niv/issues/314

Probably needs some updating or that dependency needs to be pinned to 0.15.1

I'm not a haskell expert so I haven't investigated further

**Comment by justinwoo** [comment]
Fixed by https://github.com/purescript/psc-package/pull/168. This issue is caused most likely by someone trying to use nixpkgs haskellPackages to build psc-package for some unknown reason.
