### ISSUE TITLE
psc-package sources globs miss files

### ISSUE THREAD

**Issue by matthewleon** [purescript/psc-package#17]
`psc-package sources` outputs globs that, in some cases, will miss certain modules.

For example, the glob output for the Prelude is `.psc-package/psc-0.11.3/prelude/v3.0.0/src/**/*.purs`. However, `Prelude.purs` lives directly in the `src` directory.

**Comment by garyb** [comment]
Hmm, a glob of `.psc-package/psc-0.11.3/prelude/v3.0.0/src/**/*.purs` should include `.psc-package/psc-0.11.3/prelude/v3.0.0/src/Prelude.purs` - `/**/` includes `/./` basically.

**Comment by matthewleon** [comment]
Then this is, perhaps, a problem with the glob library being used by
`purs`? If you use `Debug.Trace` to get a list of the files it finds with
that input, it will not see the file in question.

**Comment by matthewleon** [comment]
https://hackage.haskell.org/package/Glob-0.7.14/docs/System-FilePath-Glob.html

**/
Matches any number of characters, including path separators, excluding the empty string.

**Comment by garyb** [comment]
That's the same glob that `pulp`, etc. uses (well, it uses `src/**/*.purs bower_components/purescript-*/src/**/*.purs`), so it's kinda odd that it doesn't work :/

**Comment by matthewleon** [comment]
It appears that interpretation of `**` varies across libraries. Perhaps the safe thing to do is include an extra glob for `.purs` files in `src` root?

**Comment by garyb** [comment]
It definitely differs across libraries, but we're talking about sending a glob to `purs compile` in both cases here, I think?

**Comment by matthewleon** [comment]
Yes, both `purs compile` and `purs docs`.

My sense is that what me way want is to simply get rid of a single `/*`: `.psc-package/psc-0.11.3/prelude/v3.0.0/src/**.purs`

**Comment by garyb** [comment]
Sure, I'm just baffled why it doesn't work here but does for `pulp` / when I manually invoke `purs compile` with the globs I mentioned above.

**Comment by matthewleon** [comment]
I, too, am baffled. It would be nice to figure it out before proceeding to a solution. Thinking on it.

**Comment by matthewleon** [comment]
Manually running `purs compile bower_components/purescript-*/src/**/*.purs` will not find `src/Prelude.purs`.

`pulp` is doing something different. I'll add some debug statements and find out shortly... But are you sure `pulp` isn't expanding that glob internally using a different lib?

**Comment by garyb** [comment]
Maybe this is a recent change in the globbing behaviour then - when testing things I've been working on with the compiler I've definitely used the above globs manually and had it pick up cases like `Prelude.purs`. I've not tried it since 0.11.0ish though.

**Comment by matthewleon** [comment]
Ah sorry no, this was my fault. `bash` was picking up the glob itself rather than sending it as an argument to `purs`. If I quote it properly it does see what it should. (referring to the `pulp` glob... Will test on others now.)

**Comment by matthewleon** [comment]
`purs compile '.psc-package/psc-0.11.3/prelude/*/src/**/*.purs'` is working fine.
However, `purs compile $(psc-package sources)` does not. It looks like this is an issue of the shell expanding some of those blobs, but not others, for whatever reason. In any case it looks like this is not a `psc-package` issue. Closing.

**Comment by garyb** [comment]
Aha! Mystery solved :smile:

I think something like that has arisen before - since I sometimes use Windows I tend to forget that unquoted globs are recognised by bash too.

**Comment by chexxor** [comment]
I had a globbing problem with pulp, as pulp creates a sub process, and one version of node will expand the glob in the operation while another version of node does not. That is different from this issue, of course, but worth mentioning here too for other readers.
