### ISSUE TITLE
Suggestion: a document specifying the design decisions and next steps

### ISSUE THREAD

**Issue by soupi** [purescript/psc-package#2]
Since this project is now on low flame, may I suggest creating a document that specifies what is the vision/goals/next steps for this tool, and what are the common problems you ran into while designing it?

I know there has been a pretty big discussion about it, and I think having a clearer idea about your vision
for this tool and what you don't want it to include will lower the barrier of entry and will make it easier for others to continue your work and take this tool forward.

**Comment by paf31** [comment]
Sounds like a good idea. I'll try to put something together.

**Comment by soupi** [comment]
Thanks!
