### ISSUE TITLE
Add a `repl` command

### ISSUE THREAD

**Issue by soupi** [purescript/psc-package#4]
nwolverson mentioned that one can invoke psci directly using

```
psci `psc-package sources` 'src/**/*.purs'
```

However it is not entirely straightforward to discover this when you are not familiar with psc/i very much.

I'd like to suggest a `psc-package repl` command that will run the mentioned command as well as a flag for it (for example: `--only-dependencies`) that will not include `'src/**/*.purs'` (so you can have a repl with your deps even when you code doesn't compile yet).

I could probably add this command myself if needed.

**Comment by paf31** [comment]
I tried this, but I couldn't get it working. Text entry in the REPL wouldn't work. Maybe you can figure out why not. This would be nice to have.

**Comment by soupi** [comment]
Now I'm a bit worried 😟, but I will give it a try. Thanks!
