### ISSUE TITLE
Support installing purs from psc-package

### ISSUE THREAD

**Issue by polux** [purescript/psc-package#47]
It would be great if the single entrypoint to purescript was psc-package, by allowing one to install (a version of) purescript directly from the tool. Something akin to stack install.

**Comment by hdgarrood** [comment]
I think if any tool was going to do this, it would make more sense for it to be pulp - my understanding is that psc-package is not meant to be anything more than a package manager.

**Comment by polux** [comment]
Yes sorry, I read the psc-package megascript in the meantime and came to the same conclusion. Still, it might make sense for a package set to keep track of the compatible purescript compiler versions, which it doesn't seems like.

**Comment by paf31** [comment]
The package sets themselves track compiler versions, in the names of the package set branches. We could potentially add the supported compiler versions to the package set JSON though. Could you please create an issue on `package-sets`?
