### ISSUE TITLE
docs command

### ISSUE THREAD

**Issue by matthewleon** [purescript/psc-package#48]
related: https://github.com/purescript/psc-package/issues/43

Would there be any interest in having a `docs` command that generates offline documentation for the package and its dependencies using `purs docs`?

**Comment by hdgarrood** [comment]
I'm tempted to close this since `pulp` now covers this use case via its psc-package support. Thoughts?

**Comment by kritzcreek** [comment]
👍 for closing from me. I think even the `build` command was only meant as a temporary measure until `pulp` understood psc-package.
