### ISSUE TITLE
Cannot allocate memory error

### ISSUE THREAD

**Issue by seagreen** [purescript/psc-package#59]
When running `psc-package build` I sometimes get the error `psc-package: failed to create OS thread: Cannot allocate memory`. The command still seems to make progress, so after running it a couple times it succeeds. I don't think I'm actually running out of memory -- I have a few gigs free when I run the command and according to xmobar it doesn't get used up.

Version details (exhaustive setup [is here](https://github.com/seagreen/ianix/tree/39a4af23d3ac536e965ddea39895ccd0c717f041/shell/purescript)):
```
$ psc-package --version
0.2.0
$ purs --version
0.11.6
```

Example error occurances:
```
$ psc-package build
Updating 45 packages...
Updating assert
Updating arraybuffer-types
Updating arrays
Updating console
Updating control
Updating distributive
Updating datetime
Updating bifunctors
Updating eff
Updating dom
Updating either
Updating foldable-traversable
Updating enums
Updating exceptions
Updating generics
Updating functions
Updating gen
Updating identity
Updating globals
Updating foreign
Updating integers
Updating invariant
Updating lazy
Updating js-date
Updating maps
Updating lists
Updating maybe
Updating newtype
Updating media-types
Updating nonempty
Updating math
Updating monoid
Updating partial
Updating nullable
Updating prelude
Updating proxy
Updating psci-support
Updating strings
Updating st
Updating tailrec
Updating tuples
Updating transformers
Updating type-equality
Updating unfoldable
Updating unsafe-coerce
psc-package: failed to create OS thread: Cannot allocate memory

$ psc-package build
Updating 45 packages...
Updating lazy
Updating lists
Updating math
Updating maps
Updating media-types
Updating maybe
Updating monoid
Updating nonempty
Updating newtype
Updating nullable
Updating partial
Updating prelude
Updating proxy
Updating psci-support
Updating strings
Updating tailrec
Updating transformers
Updating tuples
Updating type-equality
Updating st
Updating unsafe-coerce
Updating unfoldable
psc-package: failed to create OS thread: Cannot allocate memory

$ psc-package build
<succeeds this time>
```

**Comment by paf31** [comment]
Can you please try with `+RTS -N1`?

**Comment by seagreen** [comment]
Sure! I tried `psc-package build +RTS -N1`, but got the same error.

Let me know what else I can do to help.

**Comment by paf31** [comment]
What OS are you using? I wonder if we should add a flag to make things single threaded.

**Comment by seagreen** [comment]
I'm on NixOS. Removing `-threaded` definitely fixes the problem.

Adding a flag to switch to a single thread on NixOS makes sense to me. I looked into [the easy way](https://www.haskell.org/cabal/users-guide/developing-packages.html#configurations), but `System.Info.os` just returns `"linux"`. There may be some other way to check for NixOS though that I don't know.

I could also report this on the Nixpkgs issue tracker, since it does seem like that's the only place the problem is happening.

**Comment by kwohlfahrt** [comment]
I can reproduce this bug on Debian Linux (psc-package 0.3.1, purescript 0.11.7). I know I have overcommit disabled, perhaps this is what distinguishes my setup (and NixOS) from the default linux setup?

It seems to have gone away - I was getting segmentation faults with other programs too, so perhaps there was some faulty memory or a bug in an underlying library.

**Comment by justinwoo** [comment]
I believe we have also fixed this with https://github.com/purescript/psc-package/pull/127, where this became more of a problem on CI machines.
