### ISSUE TITLE
Support non-curated package depencency in project configuration

### ISSUE THREAD

**Issue by aztecrex** [purescript/psc-package#60]
Similar to the capability in Haskell Stack, would like the ability to add packages that are not in the configured package set. Ideally it would allow for overriding curated version of a package in addition to simply adding an uncurated package.

Primary use case for me is the ability to use our domain-specific libraries.

Secondary use cases include using a needed library before it is added to package-sets, using a homegrown general-purpose library before releasing it to the community, and experimenting with a library's upcoming features before its version is updated in package-sets.

**Comment by paf31** [comment]
> Primary use case for me is the ability to use our domain-specific libraries.

The recommended solution is to make your own package set (see the README). You might want to do this by maintaining a fork, or just creating a small package set of only the packages you need.

You can also host a package set locally (even in your application repo) by using Git's `file://` URLs.

`psc-package` won't get support for overriding packages, but we might eventually add support for augmenting an existing package set with additional packages.
