### ISSUE TITLE
Improve help text

### ISSUE THREAD

**Issue by gabejohnson** [purescript/psc-package#63]
As a new `psc-package` user I struggled yesterday to perform the most basic of tasks, an initial package set install.

Neither the help text, nor the README provide any guidance in this regard. In fact, the README seems to target package authors with little thought to package users.

With some help I discovered `psc-package update` was what I needed, but that command and the associated help text `Update dependencies` have different semantics from an initial install.

I propose improving the help text for a few of the commands:

`init`        `Initialize a new package` -> `Create a new psc-package.json file`
`update` `Update dependencies` -> `Install or update package dependencies`
`build`    `Build the current package and dependencies` -> `Update dependencies and compile the current package`

Additionally, a line near the top of the README regarding initial install would be helpful. Something along the lines of:

```sh
# installs the project dependencies listed in psc-package.json
psc-package update
```

**Comment by gabejohnson** [comment]
Another option is to have `install` with no package specified be an alias for `update`

**Comment by joneshf** [comment]
I think this all seems reasonable. Any objections?

**Comment by paf31** [comment]
Sounds good
