### ISSUE TITLE
Adding packages from Bower to a package set

### ISSUE THREAD

**Issue by justinwoo** [purescript/psc-package#76]
I would really like to have this, and doing some initial searching I've found that there's no real way to get the information we need that the Bower CLI/Node library can provide through any APIs like libraries.io i.e. we need to know what dependencies a project has, and `bower info` seems to be the only convenient way to get this.

So I don't really have a good idea on how this should be done other than to call out to the Bower CLI and parse the JSON that it outputs. This would require that anyone who wants to use a add-from-bower feature to have Bower installed, but at least don't require them to have to install node or set up anything else (because otherwise we'd probably be stuck having an entire npm package here).

Thoughts?

**Comment by hdgarrood** [comment]
Seems reasonable. There is already some code in Language.PureScript.Publish which does something like this, so that might be a useful reference.

**Comment by kritzcreek** [comment]
I have some code that scrapes the Github API for releases, but it requires a Github token, because otherwise you get rate limited quickly. See https://github.com/kRITZCREEK/purs-archive/blob/99452fc446251a23f8fe2f6502cbcf07340e5c77/src/I.hs#L110-L224

Getting the package name -> repository mapping shouldn't require installing `bower` as far as I can tell.

**Comment by paf31** [comment]
Why would this need to be in psc-package though?

**Comment by justinwoo** [comment]
There's already code for how the package sets are formatted and output here right? I don't want to make a separate solution that 1) requires that people also know about and install it 2) will end up outputting changes that aren't 100% lined up with what's here.

@kRITZCREEK but you can't get the dependencies, unless you want people to manually type those in
