### ISSUE TITLE
"psc-package repl" doesn't import Prelude

### ISSUE THREAD

**Issue by philipnilsson** [purescript/psc-package#80]
Initializing a project using `psc-package init` I get a `psc-package.json` file that sets up `prelude` as a dependency. 

At this point running `psc-package repl`, I would expect `Prelude` to be automatically imported as it's a dependency of the project, but it's not. Am I having the wrong idea of what is intended with this command, or is this an improvment to be made?

**Comment by kritzcreek** [comment]
You can create a file to load whatever module you want by default in your repl session yourself by creating a `.purs-repl` file in your project root like so:
```
λ  more .\.purs-repl
import Prelude
```

You probably want to use `pulp --psc-package init` instead, which will automatically create that file for you.

**Comment by philipnilsson** [comment]
@kRITZCREEK I don't have much of a problem with working around it, was more concerned with it as a usability issue, but `pulp --psc-package init` makes a lot of sense.

**Comment by damncabbage** [comment]
Would this be a good argument for removing `psc-package init`? I argue that having two different-sort-of-ish ways to get to "a new project" result might be a bit confusing for newcomers.
