### ISSUE TITLE
Update README to reflect new Bower dependency feature

### ISSUE THREAD

**Issue by epost** [purescript/psc-package#90]
The README contains a FAQ "Can I add a dependency which is not in the package set? Not right now." This is directly under ```add-a-package-from-bower``` section. Shouldn't the FAQ be updated to say something like "yes, via Bower" now?

**Comment by hdgarrood** [comment]
I don't think so; the add-from-bower feature is just another way of adding a package to a package set, if I understand correctly.

**Comment by justinwoo** [comment]
Yeah, add from bower only affects package sets. Though, I guess with how it all works, you *could* use it in this way but your local package set changes wouldn't be put anywhere else, so nobody else could get the same.

**Comment by epost** [comment]
Got it, thanks folks!
