### ISSUE TITLE
Psc-package build shouldn't tell me "installing" over and over

### ISSUE THREAD

**Issue by justinwoo** [purescript/psc-package#99]
Just kind of unpleasant to see

**Comment by Dretch** [comment]
What should it do instead?

Should it announce what it is about to do (or perhaps, has done) - e.g. `Installing 3 packages, 32 already installed...`, or just say nothing?

**Comment by justinwoo** [comment]
Yeah, seems like it should try to do a simple check of what all changes are needed and display any worklog greater than 1

**Comment by justinwoo** [comment]
Fixed by the referenced PR
